server:
   error:
      include-stacktrace: on-param


   

      
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/times_e_jogadores?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
      username: root
      password: 123
   
   jpa:
      hibernate:
         ddl-auto: update
      show-sql: true

   mvc:
      pathmatch:
            matching-strategy: ANT_PATH_MATCHER